name: Docker
on:
  release:
    types: [published]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  check-token:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.token.outputs.defined }}
    steps:
      - id: token
        env:
            MY_TOKEN: ${{ secrets.MY_TOKEN }}
        if: "${{ env.MY_TOKEN != '' }}"
        run: echo "::set-output name=defined::true"
        
  build:
    name: Release
    runs-on: ubuntu-latest
    needs: [check-token]
    if: needs.check-token.outputs.token == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.MY_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            INCLUDE_MONGODBTOOLS=true
            PREINSTALL_LIBS=true
